# Generated by Django 5.0.6 on 2024-06-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_category_options_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("draft", "Draft")],
                default="active",
                max_length=10,
            ),
        ),
    ]
